# Decision Tree Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas 


## Importing the dataset

In [3]:
from Preprocessor import get_single_dataset
dataset = get_single_dataset("training_data/250820/test")
X = dataset.iloc[:, 2:].values
y = dataset.iloc[:, 1].values

In [4]:
X

array([[ 0. , 27. ,  0. ],
       [ 0. , 27. ,  0. ],
       [ 0. , 27. ,  0. ],
       ...,
       [ 0.4, 30. ,  0. ],
       [ 0.4, 30. ,  0. ],
       [ 0.4, 30. ,  0. ]])

In [5]:
y

array([19.769231, 19.769231, 19.769231, ..., 16.615385, 16.615385,
       16.615385])

## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Decision Tree Regression model on the Training set

In [7]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

## Predicting the Test set results

In [8]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[14.46 14.46]
 [16.86 16.85]
 [19.38 19.38]
 ...
 [14.92 14.92]
 [14.92 14.92]
 [14.92 14.92]]


## Evaluating the Model Performance

In [9]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9666654686222395